/**
 * Fails when a document points at something that is not there.
 *
 * Written after an audit found `ARCHITECTURE.md` naming `config/env.validation.ts`
 * for a file that lives at `src/config/env.validation.ts`, and describing the
 * `AUTH_REQUIRED` contract as if one frontend depended on it when all three do.
 * Neither was caught, because nothing looked.
 *
 * Five rules, all mechanical:
 *
 *   1. `npm run x` in a document must be a script in package.json.
 *   2. A backticked repository path must exist.
 *   3. A relative Markdown link must resolve.
 *   4. Every document must be reachable by following links from the README.
 *   5. `cd <dir>` must name a directory that exists, or one the document just made.
 *
 * Rule 5 is the one this repository needed. The README opened its instructions
 * with `cd server` for months after the server stopped being
 * `react-boilerplate/server/` and became this repository — so the first command a
 * reader ran failed, and nothing noticed.
 *
 * It is deliberately a rule about directories rather than about that phrase. A
 * check that banned the literal string "cd server" would pass the moment someone
 * wrote `cd ./server`, and would say nothing about any other wrong directory. It
 * would also be the shape of check this project has already deleted once: an
 * assertion about the spelling of a document rather than about whether it is
 * true. The other pre-split claims found in the same audit — a root `server:*`
 * command set that no longer exists, and "no client code points at this server" —
 * are not mechanically checkable and are not checked here. Rule 1 already catches
 * the first if it is ever written as an actual `npm run server:x`.
 *
 * Rules 3 and 4 came from the frontends, where twenty-two documents sat in the
 * root linking to each other zero times. This repository has four and already
 * links between them, so rule 4 finds nothing here today — which is the point of
 * adding it before it would.
 *
 * Historical documents are exempt from rules 1, 2 and 4. `docs/history/prompts`
 * records how each module was built and describes the layout of the time it was
 * written; rewriting those would destroy the thing they are for. They are not
 * exempt from rule 3: a record of a past layout still should not offer a link
 * that goes nowhere.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';

const ROOT = resolve(__dirname, '..', '..');
const HISTORICAL_MARKER = '<!-- doc-check: historical -->';
const HISTORICAL_DIRS = ['docs/history/'];

/** Prefixes that name something in this repository rather than an npm package or a URL. */
const PATH_ROOTS = ['src', 'prisma', 'scripts', 'tools', 'test', 'docs', 'config', 'dist'];

type Problem = { doc: string; kind: 'script' | 'path' | 'link' | 'orphan' | 'directory'; detail: string };

const KIND_LABEL: Record<Problem['kind'], string> = {
  script: 'no such script',
  path: 'no such path',
  link: 'link goes nowhere',
  orphan: 'nothing links to this document',
  directory: 'no such directory to change into',
};

/** Where the walk starts. What the README cannot reach, a reader cannot either. */
const ENTRY = 'README.md';

/** A migrations README is generated by Prisma, and history is kept rather than read. */
const NOT_LINKED_ON_PURPOSE = ['prisma/migrations/', 'docs/history/'];

/** Relative links only. An external URL is somebody else's to keep working. */
function relativeLinks(text: string): string[] {
  return [...text.matchAll(/\[[^\]]*\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g)]
    .flatMap((match) => (match[1] === undefined ? [] : [match[1]]))
    .filter((target) => !/^(?:[a-z][a-z0-9+.-]*:|\/\/|#)/i.test(target));
}

/** `docs/x.md#a-heading` and `./x.md` both name a file. */
function targetPath(doc: string, target: string): string {
  const withoutFragment = target.split(/[#?]/)[0] ?? '';

  return relative(ROOT, resolve(ROOT, dirname(doc), withoutFragment)).replace(/\\/g, '/');
}

function trackedDocs(): string[] {
  return execFileSync('git', ['ls-files', '*.md'], { cwd: ROOT, encoding: 'utf8' })
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);
}

/**
 * Directories the document itself creates before entering them.
 *
 * The non-ASCII reproduction in the README does `mkdir t` and then `cd t`, which
 * is correct and would fail a rule that only asked whether `t` is in the
 * repository.
 */
function createdHere(text: string): Set<string> {
  return new Set([...text.matchAll(/\bmkdir(?:\s+-p)?\s+([A-Za-z0-9_./-]+)/g)].flatMap((match) => (match[1] === undefined ? [] : [match[1]])));
}

function isHistorical(doc: string, text: string): boolean {
  return HISTORICAL_DIRS.some((dir) => doc.startsWith(dir)) || text.includes(HISTORICAL_MARKER);
}

function main(): void {
  const packageJson = JSON.parse(readFileSync(resolve(ROOT, 'package.json'), 'utf8')) as {
    scripts?: Record<string, string>;
  };
  const scripts = new Set(Object.keys(packageJson.scripts ?? {}));
  const problems: Problem[] = [];
  const docs = trackedDocs();

  const linksOut = new Map<string, string[]>();

  for (const doc of docs) {
    const text = readFileSync(resolve(ROOT, doc), 'utf8');
    const targets = relativeLinks(text).map((target) => targetPath(doc, target));

    linksOut.set(doc, targets);

    for (const target of targets) {
      if (target === '' || target.startsWith('..')) continue;
      if (!existsSync(resolve(ROOT, target))) problems.push({ doc, kind: 'link', detail: target });
    }

    if (isHistorical(doc, text)) continue;

    const created = createdHere(text);

    for (const match of text.matchAll(/(?:^|[;&|]|&&)\s*cd\s+([A-Za-z0-9_./-]+)/gm)) {
      const target = match[1];

      if (target === undefined) continue;
      // Somewhere else on the machine, not a claim about this repository.
      if (target.startsWith('~') || target.startsWith('/') || target.startsWith('..')) continue;
      if (created.has(target)) continue;

      const normalised = target.replace(/^\.\//, '');

      if (!existsSync(resolve(ROOT, normalised))) problems.push({ doc, kind: 'directory', detail: `cd ${target}` });
    }

    for (const match of text.matchAll(/npm run ([a-z0-9:_-]+)/g)) {
      const script = match[1];
      if (script === undefined) continue;
      if (!scripts.has(script)) problems.push({ doc, kind: 'script', detail: `npm run ${script}` });
    }

    for (const match of text.matchAll(/`((?:[A-Za-z0-9_.-]+\/)+[A-Za-z0-9_.*-]*)`/g)) {
      const candidate = match[1];
      if (candidate === undefined) continue;
      const root = candidate.split('/')[0];
      if (root === undefined || !PATH_ROOTS.includes(root)) continue;
      // Globs and placeholders describe a shape, not a file.
      if (/[*{}<>]/.test(candidate)) continue;
      if (!existsSync(resolve(ROOT, candidate))) problems.push({ doc, kind: 'path', detail: candidate });
    }
  }

  const reached = new Set<string>([ENTRY]);
  const queue = [ENTRY];

  while (queue.length > 0) {
    const current = queue.shift();
    if (current === undefined) continue;

    for (const target of linksOut.get(current) ?? []) {
      if (!target.endsWith('.md') || reached.has(target)) continue;
      reached.add(target);
      queue.push(target);
    }
  }

  for (const doc of docs) {
    if (reached.has(doc)) continue;
    if (NOT_LINKED_ON_PURPOSE.some((prefix) => doc.startsWith(prefix))) continue;
    problems.push({ doc, kind: 'orphan', detail: `not reachable from ${ENTRY}` });
  }

  if (problems.length === 0) {
    console.log(`docs:check — ${docs.length} documents, ${reached.size} reachable from ${ENTRY}, nothing stale.`);
    return;
  }

  console.error('Documents reference things that do not exist:\n');
  for (const { doc, kind, detail } of problems) {
    console.error(`  ${doc}: ${KIND_LABEL[kind]} — ${detail}`);
  }
  console.error(
    `\n${problems.length} problem(s). Fix the document, link it from ${ENTRY}, or mark it historical with ${HISTORICAL_MARKER} if it records a past state on purpose.`,
  );
  process.exit(1);
}

main();
